config_token.settings:
  type: config_object
  label: 'Config Token Settings'
  mapping:
    allowed_tokens:
      type: sequence
      label: 'Allowed tokens'
      sequence:
        type: mapping
        label: 'Token'
        mapping:
          name:
            type: string
            label: 'Name'
          description:
            type: string
            label: 'Description'
          format_id:
            type: string
            label: 'Format id e.g. plain_text'
