config_token.tokens:
  type: config_object
  label: 'Tokens with respective values'
  mapping:
    replacements:
      type: sequence
      label: 'Token replacements'
      sequence:
        type: string
